esphome:
  name: speakers
  friendly_name: Колонки
  on_boot:
    - priority: 600
      then:
        - output.turn_off: encoder_optocoupler

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

network:
  enable_ipv6: true

openthread:
  device_type: FTD
  tlv: !secret thread_tlv

substitutions:
  monitoring_mode: GPIO19
  music_mode: GPIO18
  button_pin: GPIO20

# Описание выходов
output:
  - platform: gpio
    pin: $button_pin
    id: encoder_optocoupler

binary_sensor:
  # Датчики от оптопар светодиодов
  - platform: gpio
    pin:
      number: $monitoring_mode
      mode: INPUT_PULLUP
      inverted: true
    id: led_red_raw
    internal: true

  - platform: gpio
    pin:
      number: $music_mode
      mode: INPUT_PULLUP
      inverted: true
    id: led_green_raw
    internal: true

  # --- ЛОГИКА СОСТОЯНИЙ ---
  # 1. Питание: включено, если горит/мигает любой диод
  - platform: template
    id: amp_is_on
    internal: true
    lambda: 'return id(led_red_raw).state || id(led_green_raw).state;'
    filters:
      - delayed_off: 700ms

  # 2. Mute: включено, если питание есть, но диоды сейчас в фазе "выкл"
  - platform: template
    id: amp_is_muted
    internal: true
    lambda: |-
      return id(amp_is_on).state && (!id(led_red_raw).state && !id(led_green_raw).state);
    filters:
      - delayed_on: 200ms
      - delayed_off: 1200ms

  # 3. Индикаторы конкретных режимов (для меню)
  - platform: template
    id: is_monitoring
    internal: true
    lambda: 'return id(led_red_raw).state;'
    filters:
      - delayed_off: 700ms

  - platform: template
    id: is_music
    internal: true
    lambda: 'return id(led_green_raw).state;'
    filters:
      - delayed_off: 700ms

switch:
  # ПЕРЕКЛЮЧАТЕЛЬ ПИТАНИЯ (Удержание 2 сек)
  - platform: template
    name: "Колонки"
    id: sw_power
    icon: "mdi:speaker-multiple"
    lambda: 'return id(amp_is_on).state;'
    turn_on_action:
      - if:
          condition: {lambda: 'return !id(amp_is_on).state;'}
          then:
            - output.turn_on: encoder_optocoupler
            - delay: 2000ms
            - output.turn_off: encoder_optocoupler
    turn_off_action:
      - if:
          condition: {lambda: 'return id(amp_is_on).state;'}
          then:
            - output.turn_on: encoder_optocoupler
            - delay: 2000ms
            - output.turn_off: encoder_optocoupler

  # ПЕРЕКЛЮЧАТЕЛЬ БЕЗ ЗВУКА
  - platform: template
    name: "Без звука"
    id: sw_mute
    icon: "mdi:volume-mute"
    lambda: 'return id(amp_is_muted).state;'
    # Блокируем клик, если питание выключено
    turn_on_action:
      - if:
          condition: {lambda: 'return id(amp_is_on).state && !id(amp_is_muted).state;'}
          then:
            - output.turn_on: encoder_optocoupler
            - delay: 200ms
            - output.turn_off: encoder_optocoupler
    turn_off_action:
      - if:
          condition: {lambda: 'return id(amp_is_muted).state;'}
          then:
            - output.turn_on: encoder_optocoupler
            - delay: 200ms
            - output.turn_off: encoder_optocoupler

select:
  - platform: template
    name: "Режим"
    id: amp_mode_select
    icon: "mdi:tune"
    options:
      - "Мониторинг"
      - "Музыка"
    # ОБРАТНАЯ СВЯЗЬ: заставляет интерфейс HA меняться вслед за светодиодами
    lambda: |-
      if (id(is_monitoring).state) return std::string("Мониторинг");
      if (id(is_music).state) return std::string("Музыка");
      return {};

    # ПЕРЕКЛЮЧЕНИЕ
    set_action:
      - if:
          condition:
            lambda: |-
              bool want_music = (x == "Музыка");
              // Переключаем только если режим в HA не совпадает с реальным свечением диода
              return id(amp_is_on).state && (want_music != id(is_music).state);
          then:
            - output.turn_on: encoder_optocoupler
            - delay: 100ms # Первое нажатие
            - output.turn_off: encoder_optocoupler
            - delay: 100ms # Увеличенная пауза между кликами для надежности
            - output.turn_on: encoder_optocoupler
            - delay: 100ms # Второе нажатие
            - output.turn_off: encoder_optocoupler
